name = "crypto-daily-worker"
main = "src/index.ts"
compatibility_date = "2026-03-05"

[[routes]]
pattern = "crypto-api.bhwa233.com"
custom_domain = true
zone_name = "bhwa233.com"

[triggers]
crons = ["5 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "crypto-daily"
database_id = "21a1a3a0-bd0b-44a7-88e1-272430fe8ca0"

[ai]
binding = "AI"

[vars]
