name = "china-stocks-daily-worker"
main = "src/index.ts"
compatibility_date = "2026-03-05"

[triggers]
crons = ["0 23 * * 1-5"]

[[d1_databases]]
binding = "DB"
database_name = "china-stocks-daily"
database_id = ""

# Optional vars for OpenAI-compatible providers.
[vars]
OPENAI_BASE_URL = ""
AI_MODEL = "gpt-5.2"
ADMIN_TOKEN= ""
OPENAI_API_KEY=""
