/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

type Fetcher = {
  fetch(input: Request | string | URL, init?: RequestInit): Promise<Response>;
};

interface Env {
  ASSETS: Fetcher;
  STOCKS_API: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

const REPORT_DATE_PATH = /^\/report\/\d{4}-\d{2}-\d{2}$/;
const API_STATIC_PATHS = new Set(["/health", "/latest", "/reports", "/rss.xml", "/atom.xml", "/feed.json"]);

function resolveApiPath(pathname: string): string | null {
  if (pathname === "/rss.xml" || pathname === "/atom.xml" || pathname === "/feed.json") {
    return pathname;
  }

  if (!pathname.startsWith("/api/")) {
    return null;
  }

  const apiPath = pathname.slice(4) || "/";
  if (API_STATIC_PATHS.has(apiPath) || REPORT_DATE_PATH.test(apiPath)) {
    return apiPath;
  }

  return null;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    const apiPath = resolveApiPath(url.pathname);
    if (apiPath) {
      const upstreamUrl = new URL(`https://stocks-api.internal${apiPath}${url.search}`);
      return env.STOCKS_API.fetch(new Request(upstreamUrl.toString(), request));
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Delegate everything else to vinext
    return handler.fetch(request);
  },
};
