/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES, handleImageOptimization } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

type Fetcher = {
  fetch(input: Request | string | URL, init?: RequestInit): Promise<Response>;
};

type RequestWithCf = Request & {
  cf?: {
    country?: string;
  };
};

interface Env {
  ASSETS: Fetcher;
  MARKETS_API?: Fetcher;
  MARKETS_API_BASE_URL?: string;
  APP_ENV?: string;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

type ApiRouteTarget = {
  upstreamPath: string;
};

type ApiUpstreamSource = "service-binding" | "fallback-public-api";
type ApiProxyErrorSource = "service-binding-error" | "fallback-public-api-error";

const DEFAULT_API_BASE_URL = "https://china-stocks-daily-worker.404174262.workers.dev";
const ADMIN_SESSION_API_PATH = "/api/admin/session";
const ADMIN_SESSION_COOKIE = "stocks-admin-session";
const ADMIN_SESSION_MAX_AGE_SECONDS = 60 * 60 * 12;
const PROXY_UPSTREAM_TIMEOUT_MS = 20_000;
const APP_HANDLER_TIMEOUT_MS = 30_000;
const API_UPSTREAM_HEADER = "x-api-upstream";
const API_UPSTREAM_RAY_HEADER = "x-api-upstream-cf-ray";
const API_UPSTREAM_NOTE_HEADER = "x-api-upstream-note";
const HOP_BY_HOP_HEADERS = new Set([
  "connection",
  "content-length",
  "host",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "te",
  "trailer",
  "transfer-encoding",
  "upgrade"
]);

class ResponseTimeoutError extends Error {
  constructor(readonly label: string, readonly timeoutMs: number) {
    super(`${label} timed out after ${timeoutMs}ms.`);
    this.name = "ResponseTimeoutError";
  }
}

function isLocalDevHost(hostname: string): boolean {
  return hostname === "localhost" || hostname === "127.0.0.1" || hostname.endsWith(".localhost");
}

function resolveCountryCodes(request: Request): string[] {
  const requestWithCf = request as RequestWithCf;
  const requestCountry =
    typeof requestWithCf.cf === "object" &&
    requestWithCf.cf &&
    "country" in requestWithCf.cf &&
    typeof requestWithCf.cf.country === "string"
      ? requestWithCf.cf.country
      : null;
  const values = [
    requestCountry,
    request.headers.get("x-country-code"),
    request.headers.get("cf-ipcountry")
  ];

  return [...new Set(values.map((value) => value?.trim().toUpperCase()).filter((value): value is string => Boolean(value)))];
}

function resolveApiTarget(pathname: string): ApiRouteTarget | null {
  if (pathname === "/api" || pathname === "/api/") {
    return { upstreamPath: "/api/v1/stocks/" };
  }

  if (pathname.startsWith("/api/v1/")) {
    return { upstreamPath: pathname };
  }

  if (pathname.startsWith("/api/crypto/")) {
    const subPath = pathname.slice("/api/crypto".length) || "/";
    return { upstreamPath: `/api/v1/crypto${subPath}` };
  }

  if (pathname.startsWith("/api/status/")) {
    const subPath = pathname.slice("/api".length) || "/";
    return { upstreamPath: `/api/v1${subPath}` };
  }

  if (pathname.startsWith("/api/")) {
    const subPath = pathname.slice("/api".length) || "/";
    return { upstreamPath: `/api/v1/stocks${subPath}` };
  }

  return null;
}

function parseCookieHeader(cookieHeader: string | null): Map<string, string> {
  const values = new Map<string, string>();
  if (!cookieHeader) {
    return values;
  }

  for (const part of cookieHeader.split(";")) {
    const [rawName, ...rawValueParts] = part.split("=");
    const name = rawName?.trim();
    if (!name) {
      continue;
    }
    const rawValue = rawValueParts.join("=").trim();
    try {
      values.set(name, decodeURIComponent(rawValue));
    } catch {
      values.set(name, rawValue);
    }
  }

  return values;
}

function getAdminSessionToken(request: Request): string | null {
  const token = parseCookieHeader(request.headers.get("cookie")).get(ADMIN_SESSION_COOKIE)?.trim();
  return token ? token : null;
}

function buildAdminSessionCookie(requestUrl: URL, token: string | null): string {
  const parts = [`${ADMIN_SESSION_COOKIE}=${token ? encodeURIComponent(token) : ""}`, "Path=/", "HttpOnly", "SameSite=Strict"];

  if (!isLocalDevHost(requestUrl.hostname)) {
    parts.push("Secure");
  }

  if (token) {
    parts.push(`Max-Age=${ADMIN_SESSION_MAX_AGE_SECONDS}`);
  } else {
    parts.push("Expires=Thu, 01 Jan 1970 00:00:00 GMT", "Max-Age=0");
  }

  return parts.join("; ");
}

function resolveFallbackApiBaseUrl(env: Env): string {
  const configured = env.MARKETS_API_BASE_URL?.trim();
  return (configured && configured.length > 0 ? configured : DEFAULT_API_BASE_URL).replace(/\/+$/, "");
}

function isLocalAppEnv(env: Env): boolean {
  return env.APP_ENV?.trim().toLowerCase() === "local";
}

function applyNoStoreCacheHeaders(headers: Headers): void {
  headers.set("cache-control", "no-store, no-cache, must-revalidate, max-age=0");
  headers.set("pragma", "no-cache");
  headers.set("expires", "0");
}

function shouldUseServiceBinding(env: Env): boolean {
  return Boolean(env.MARKETS_API);
}

async function shouldFallbackToPublicApi(response: Response): Promise<boolean> {
  if (response.status < 500) {
    return false;
  }

  const body = await response.clone().text();
  return response.status === 502 || response.status === 503 || response.status === 504 || body.includes("local dev session");
}

function withApiProxyHeaders(
  response: Response,
  source: ApiUpstreamSource,
  note?: string,
  sessionCookie?: string,
  disableCache = false
): Response {
  const headers = new Headers(response.headers);
  headers.set(API_UPSTREAM_HEADER, source);
  if (disableCache) {
    applyNoStoreCacheHeaders(headers);
  }

  const upstreamCfRay = response.headers.get("cf-ray");
  if (upstreamCfRay) {
    headers.set(API_UPSTREAM_RAY_HEADER, upstreamCfRay);
  }

  if (note) {
    headers.set(API_UPSTREAM_NOTE_HEADER, note);
  }

  if (sessionCookie) {
    headers.append("set-cookie", sessionCookie);
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers
  });
}

function createProxyHeaders(request: Request, injectedAdminToken?: string): Headers {
  const headers = new Headers();

  for (const [key, value] of request.headers.entries()) {
    const lowerKey = key.toLowerCase();
    if (HOP_BY_HOP_HEADERS.has(lowerKey) || lowerKey === "cookie") {
      continue;
    }
    headers.set(key, value);
  }

  const countryCode = resolveCountryCodes(request)[0];
  if (countryCode) {
    headers.set("x-country-code", countryCode);
  }

  if (injectedAdminToken && !headers.has("x-admin-token")) {
    headers.set("x-admin-token", injectedAdminToken);
  }

  return headers;
}

function createProxyRequest(targetUrl: string, request: Request, injectedAdminToken?: string): Request {
  const init: RequestInit = {
    method: request.method,
    headers: createProxyHeaders(request, injectedAdminToken),
    redirect: request.redirect
  };

  if (request.method !== "GET" && request.method !== "HEAD") {
    init.body = request.body;
  }

  return new Request(targetUrl, init);
}

function toErrorMessage(error: unknown): string {
  if (error instanceof Error && error.message) {
    return error.message;
  }

  return String(error);
}

async function withTimeout<T>(promise: Promise<T>, timeoutMs: number, label: string): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const timeoutPromise = new Promise<never>((_resolve, reject) => {
    timer = setTimeout(() => reject(new ResponseTimeoutError(label, timeoutMs)), timeoutMs);
  });

  try {
    return await Promise.race([promise, timeoutPromise]);
  } finally {
    if (timer) {
      clearTimeout(timer);
    }
  }
}

function createApiProxyErrorResponse(
  source: ApiProxyErrorSource,
  message: string,
  note?: string,
  disableCache = false,
  status = 502
): Response {
  const headers = new Headers({
    "content-type": "text/plain; charset=utf-8",
    [API_UPSTREAM_HEADER]: source
  });
  if (disableCache) {
    applyNoStoreCacheHeaders(headers);
  }

  if (note) {
    headers.set(API_UPSTREAM_NOTE_HEADER, note);
  }

  return new Response(message, {
    status,
    statusText: status === 504 ? "Gateway Timeout" : "Bad Gateway",
    headers
  });
}

async function proxyApiRequest(
  request: Request,
  requestUrl: URL,
  env: Env,
  options?: { overrideAdminToken?: string | null }
): Promise<Response> {
  const target = resolveApiTarget(requestUrl.pathname);
  if (!target) {
    return new Response("Not Found", { status: 404 });
  }

  const serviceBinding = env.MARKETS_API;
  const upstreamUrl = new URL(`https://markets-api.internal${target.upstreamPath}${requestUrl.search}`);
  const useServiceBinding = shouldUseServiceBinding(env);
  const explicitAdminToken = request.headers.get("x-admin-token");
  const sessionAdminToken = getAdminSessionToken(request);
  const injectedAdminToken = explicitAdminToken ?? options?.overrideAdminToken ?? sessionAdminToken ?? undefined;
  const disableCache = isLocalAppEnv(env) || isLocalDevHost(requestUrl.hostname);
  const shouldClearSessionOnUnauthorized = !explicitAdminToken && !!sessionAdminToken;
  const sessionCookieToClear = shouldClearSessionOnUnauthorized ? buildAdminSessionCookie(requestUrl, null) : undefined;
  const requestForServiceBinding = useServiceBinding && serviceBinding ? request.clone() : null;
  const requestForFallback = requestForServiceBinding ? request.clone() : request;

  if (useServiceBinding && serviceBinding && requestForServiceBinding) {
    try {
      const proxied = await withTimeout(
        serviceBinding.fetch(
          createProxyRequest(upstreamUrl.toString(), requestForServiceBinding, injectedAdminToken)
        ),
        PROXY_UPSTREAM_TIMEOUT_MS,
        `service-binding ${requestUrl.pathname}`
      );
      if (!(await shouldFallbackToPublicApi(proxied))) {
        const tagged = withApiProxyHeaders(
          proxied,
          "service-binding",
          undefined,
          proxied.status === 401 ? sessionCookieToClear : undefined,
          disableCache
        );
        console.log(`[API_PROXY] ${requestUrl.pathname} -> service-binding (${tagged.status})`);
        return tagged;
      }
    } catch (error) {
      console.error(`[API_PROXY] ${requestUrl.pathname} service-binding error: ${toErrorMessage(error)}`);
    }
  }

  const fallbackApiUrl = new URL(`${resolveFallbackApiBaseUrl(env)}${target.upstreamPath}${requestUrl.search}`);
  if (fallbackApiUrl.origin === requestUrl.origin) {
    return new Response("MARKETS_API_BASE_URL cannot point to the same web worker origin.", { status: 500 });
  }

  const note = useServiceBinding
    ? isLocalDevHost(fallbackApiUrl.hostname)
      ? "binding-fallback-local-api"
      : "binding-fallback"
    : isLocalDevHost(fallbackApiUrl.hostname)
      ? "no-binding-local-api"
      : isLocalDevHost(requestUrl.hostname)
        ? "local-dev-remote-api"
        : "no-binding";

  try {
    const fallbackResponse = await withTimeout(
      fetch(createProxyRequest(fallbackApiUrl.toString(), requestForFallback, injectedAdminToken)),
      PROXY_UPSTREAM_TIMEOUT_MS,
      `fallback-public-api ${requestUrl.pathname}`
    );
    const tagged = withApiProxyHeaders(
      fallbackResponse,
      "fallback-public-api",
      note,
      fallbackResponse.status === 401 ? sessionCookieToClear : undefined,
      disableCache
    );
    console.log(`[API_PROXY] ${requestUrl.pathname} -> fallback-public-api (${tagged.status}, ${note})`);
    return tagged;
  } catch (error) {
    const message = `API proxy request failed for ${requestUrl.pathname}: ${toErrorMessage(error)}`;
    console.error(`[API_PROXY] ${requestUrl.pathname} fallback-public-api error (${note}): ${toErrorMessage(error)}`);
    return createApiProxyErrorResponse(
      "fallback-public-api-error",
      message,
      note,
      disableCache,
      error instanceof ResponseTimeoutError ? 504 : 502
    );
  }
}

async function validateAdminToken(request: Request, requestUrl: URL, env: Env, token: string): Promise<Response> {
  const validationUrl = new URL(requestUrl.toString());
  validationUrl.pathname = "/api/stocks";
  validationUrl.search = "?includeInactive=true";
  const validationRequest = new Request(validationUrl.toString(), {
    method: "GET",
    headers: new Headers({
      accept: "application/json",
      "x-admin-token": token
    })
  });

  return proxyApiRequest(validationRequest, validationUrl, env);
}

async function handleAdminSessionRequest(request: Request, requestUrl: URL, env: Env): Promise<Response> {
  if (request.method === "GET") {
    const sessionToken = getAdminSessionToken(request);
    if (!sessionToken) {
      return Response.json(
        { authenticated: false },
        {
          status: 401,
          headers: { "cache-control": "no-store" }
        }
      );
    }

    const validationResponse = await validateAdminToken(request, requestUrl, env, sessionToken);
    if (!validationResponse.ok) {
      return Response.json(
        { authenticated: false },
        {
          status: validationResponse.status === 401 ? 401 : validationResponse.status,
          headers: {
            "cache-control": "no-store",
            "set-cookie": buildAdminSessionCookie(requestUrl, null)
          }
        }
      );
    }

    return Response.json(
      { authenticated: true },
      {
        headers: { "cache-control": "no-store" }
      }
    );
  }

  if (request.method === "POST") {
    let payload: unknown = null;
    try {
      payload = await request.json();
    } catch {
      payload = null;
    }

    const token =
      payload && typeof payload === "object" && "token" in payload && typeof payload.token === "string"
        ? payload.token.trim()
        : "";

    if (!token) {
      return new Response("管理员令牌不能为空。", { status: 400 });
    }

    const validationResponse = await validateAdminToken(request, requestUrl, env, token);
    if (!validationResponse.ok) {
      const message = await validationResponse.text();
      return new Response(message || "Unauthorized.", {
        status: validationResponse.status
      });
    }

    return Response.json(
      { authenticated: true },
      {
        headers: {
          "cache-control": "no-store",
          "set-cookie": buildAdminSessionCookie(requestUrl, token)
        }
      }
    );
  }

  if (request.method === "DELETE") {
    return new Response(null, {
      status: 204,
      headers: {
        "cache-control": "no-store",
        "set-cookie": buildAdminSessionCookie(requestUrl, null)
      }
    });
  }

  return new Response("Method Not Allowed", {
    status: 405,
    headers: { allow: "GET, POST, DELETE" }
  });
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    try {
      if (url.pathname === ADMIN_SESSION_API_PATH) {
        return await withTimeout(
          handleAdminSessionRequest(request, url, env),
          PROXY_UPSTREAM_TIMEOUT_MS,
          `admin-session ${url.pathname}`
        );
      }

      if (resolveApiTarget(url.pathname)) {
        return await withTimeout(proxyApiRequest(request, url, env), PROXY_UPSTREAM_TIMEOUT_MS, `api-proxy ${url.pathname}`);
      }

      if (url.pathname === "/_vinext/image") {
        const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
        return await withTimeout(
          handleImageOptimization(
            request,
            {
              fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
              transformImage: async (body, { width, format, quality }) => {
                const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
                return result.response();
              }
            },
            allowedWidths
          ),
          APP_HANDLER_TIMEOUT_MS,
          "image-optimization"
        );
      }

      return await withTimeout(handler.fetch(request, env, ctx), APP_HANDLER_TIMEOUT_MS, `app-handler ${url.pathname}`);
    } catch (error) {
      const headers = new Headers({ "content-type": "text/plain; charset=utf-8" });
      if (isLocalAppEnv(env) || isLocalDevHost(url.hostname)) {
        applyNoStoreCacheHeaders(headers);
      }

      if (error instanceof ResponseTimeoutError) {
        console.error(`[WORKER_TIMEOUT] ${url.pathname}: ${error.message}`);
        return new Response(`Worker timeout: ${error.message}`, {
          status: 504,
          statusText: "Gateway Timeout",
          headers
        });
      }

      const message = toErrorMessage(error);
      console.error(`[WORKER_ERROR] ${url.pathname}: ${message}`);
      return new Response(`Worker request failed: ${message}`, {
        status: 500,
        statusText: "Internal Server Error",
        headers
      });
    }
  }
};
